[package]
name = "xtauri"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh2 = "0.9"
confy = "0.6"
dirs = "5.0"
chrono = "0.4"
flume = "0.11"
tokio = { version = "1.38", features = ["full"] }
tokio-macros = "2.3.0"
tracing = "0.1"
tracing-subscriber = "0.3"
mio = { version = "0.8", features = ["os-poll", "os-ext", "net"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = "0.18.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
